spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bd_post?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  servlet:
    context-path: /post-service
  port: 8080